name: Laravel CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install Dependencies
      run: composer install --no-scripts

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Run migrations
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: database.mysql
      run: |
        touch database/database.mysql
        php artisan migrate

    - name: Run Tests
      run: vendor/bin/phpunit
